# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='picture',
            field=models.ImageField(blank=None, default='', null=None, upload_to=''),
        ),
    ]
