# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 17:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 16, 17, 7, 29, 228344, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
