# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_weight',
            field=models.FloatField(default=0.0),
        ),
    ]
