# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_sku_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=None, default='', max_length=64, null=None)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chip_vendor', to='order.Vendor')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='rf_id',
        ),
        migrations.AddField(
            model_name='sku',
            name='rfid',
            field=models.CharField(blank=None, default='', max_length=64, null=None),
        ),
        migrations.AddField(
            model_name='order',
            name='chip',
            field=models.ForeignKey(blank=None, default='', null=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_chip', to='order.Chip'),
        ),
    ]
