# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20160323_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='chip',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_chip', to='order.Chip'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sku',
            name='rfid',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
