# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_cart_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='username',
        ),
    ]
